# -*- coding: utf-8 -*-
"""CODTECH_AI_TASK1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19ywv0UVop6jioxCdvfWj4TBVogFNPGqE
"""

# ======================================================
# Title: Article Summarizer using BART (NLP & Transformers)
# Author: Your Name
# Description: Summarizes long articles into concise text
# Dependencies: transformers, torch
# ======================================================

# 1. Install dependencies (only run this once in your terminal):
# pip install transformers torch

# 2. Import necessary library
from transformers import pipeline

# 3. Load the pre-trained BART summarization pipeline
summarizer = pipeline("summarization", model="facebook/bart-large-cnn")

# 4. Input: Long article text to be summarized
input_text = """
Artificial Intelligence (AI) has transformed many industries by automating tasks, providing insights from data,
and enabling the development of intelligent systems. One of the most important Natural Language Processing (NLP)
techniques is summarization, which helps users quickly understand large bodies of text. There are two main
types of summarization: extractive (selecting key sentences) and abstractive (generating new summarized sentences).

With the advancement of deep learning, transformer models such as BERT, GPT, and BART have significantly improved
text summarization. BART, a sequence-to-sequence model trained to denoise corrupted text, has proven effective
in generating fluent and context-aware summaries. This script demonstrates how to use the BART model to create
a short summary of a longer article, allowing users to consume critical information more efficiently.
"""

# 5. Generate summary (adjust min_length and max_length as needed)
summary = summarizer(input_text, max_length=130, min_length=30, do_sample=False)

# 6. Output: Display the summarized text
print("\n📝 Original Article:\n")
print(input_text)

print("\n✅ Summary:\n")
print(summary[0]['summary_text'])